version: "3"
services:
  dev:
    build: dev
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "4301:5901"
      - "4322:22"
  user:
    build: user
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "4201:5901"
      - "4222:22"
